version: "3.6"

networks:
  default:
    name: f1_edge

services:
  air-mosquitto:
    container_name: mosquitto01
    image: eclipse-mosquitto
#    volumes:
#      - mosquitto.conf:/mosquitto/config/mosquitto.conf 
#      - /mosquitto/data
#      - /mosquitto/log
    ports:
      - 0.0.0.0:1883:1883
      - 0.0.0.0:9001:9001
